=== maybites/Prj_Px1m0dBridge/Prj_Px1m0dBridge/data/schemas/plugTypes.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
            elementFormDefault="qualified"
            xmlns="http://maybites.ch/px1m0d/plugTypesSchema" 
            targetNamespace="http://maybites.ch/px1m0d/plugTypesSchema">

    <xsd:element name="plugTree" type="plugTree"></xsd:element>


    <xsd:complexType name="plugTree">
        <xsd:sequence minOccurs="1" maxOccurs="unbounded">
    		<xsd:element name="plug" type="plug"></xsd:element>
    	</xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="plug">
        <xsd:all minOccurs="1" maxOccurs="1">
    		<xsd:element name="parameter" type="parameter"></xsd:element>
    	</xsd:all>
    	<xsd:attribute name="path" type="xsd:string"></xsd:attribute>
    	<xsd:attribute name="name" type="xsd:string"></xsd:attribute>
    </xsd:complexType>

    <xsd:complexType name="parameter">
        <xsd:all maxOccurs="1" minOccurs="0">
    		<xsd:element name="jobs" type="jobs"></xsd:element>
    	</xsd:all>
    </xsd:complexType>

    <xsd:complexType name="jobs">
        <xsd:sequence minOccurs="1" maxOccurs="unbounded">
    		<xsd:element name="job" type="job"></xsd:element>
    	</xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="job">
        <xsd:all>
        	<xsd:element name="message" type="message"></xsd:element>
        </xsd:all>


        <xsd:attribute name="id" type="xsd:int" use="optional"></xsd:attribute>
    	<xsd:attribute name="name" type="xsd:string" use="required"></xsd:attribute>
    	<xsd:attribute name="description" type="xsd:string"
    		use="optional">
    	</xsd:attribute>
    </xsd:complexType>

    <xsd:complexType name="midi">
    	<xsd:sequence>
    		<xsd:element name="status" type="status" minOccurs="1"
    			maxOccurs="1">
    		</xsd:element>
    		<xsd:element name="data" type="xsd:string" minOccurs="1"
    			maxOccurs="unbounded">
    		</xsd:element>
    	</xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="status">
    	<xsd:attribute name="channel" type="xsd:string"
    		use="optional">
    	</xsd:attribute>
    	<xsd:attribute name="type" type="xsd:string" use="required"></xsd:attribute>
    </xsd:complexType>




    <xsd:complexType name="osc">
        <xsd:sequence>
    		<xsd:element name="addOscString" type="xsd:string" minOccurs="0" maxOccurs="unbounded"></xsd:element>
    		<xsd:element name="addOscInt" type="xsd:string" minOccurs="0" maxOccurs="unbounded"></xsd:element>
    		<xsd:element name="addOscFloat" type="xsd:string" minOccurs="0" maxOccurs="unbounded"></xsd:element>
    	</xsd:sequence>
    	<xsd:attribute name="address" type="xsd:string" use="required"></xsd:attribute>
    	<xsd:attribute name="path" type="xsd:string" use="required"></xsd:attribute>
    </xsd:complexType>

    <xsd:complexType name="pipe">
        <xsd:all minOccurs="1" maxOccurs="1">
    		<xsd:element name="value" type="value" minOccurs="1" maxOccurs="1"></xsd:element>
    	</xsd:all>
    	<xsd:attribute name="channel" type="xsd:string" use="required">
    	</xsd:attribute>
    </xsd:complexType>

    <xsd:complexType name="message" mixed="true"><xsd:complexContent><xsd:extension base="xsd:anyType">
                <xsd:all>
                    <xsd:element name="target" type="target" maxOccurs="1">
    		</xsd:element>
                    <xsd:element name="osc" type="osc">
    		</xsd:element>
                    <xsd:element name="pipe" type="pipe"></xsd:element>
                    <xsd:element name="midi" type="midi">
    		</xsd:element>
    	</xsd:all>
                    	
                <xsd:attribute name="trigger" type="xsd:string"></xsd:attribute>
                    
            </xsd:extension></xsd:complexContent></xsd:complexType>

    <xsd:complexType name="target">
    	<xsd:choice minOccurs="1" maxOccurs="1">
    		<xsd:element name="sendToWorld" type="xsd:string"></xsd:element>
    		<xsd:element name="sendToSocketID" type="xsd:string"></xsd:element>
    		<xsd:element name="sendToPlugID" type="xsd:string"></xsd:element>
    		<xsd:element name="sendToRow" type="xsd:string"></xsd:element>
    		<xsd:element name="sendToCollum" type="xsd:string"></xsd:element>
    		<xsd:element name="sendToNeighbour" type="xsd:string"></xsd:element>
    	</xsd:choice>
    </xsd:complexType>



    <xsd:complexType name="value">
    	<xsd:attribute name="type" type="xsd:string" use="required"></xsd:attribute>
    </xsd:complexType>

</xsd:schema>

=== maybites/Prj_Px1m0dBridge/Prj_Px1m0dBridge/data/plug/types/Live/QuickTeacher1.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<plugTree xmlns="http://maybites.ch/px1m0d/plugTypesSchema"
     xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
     xsi:schemaLocation="http://maybites.ch/px1m0d/plugTypesSchema file:./data/schemas/plugTypes.xsd">
    <plug path="ch.maybites.px1m0d.plug.collection.liveA.PlgChainLink" name="QuickTeacherOne">
    	<parameter>
    		<display>
    			<icon path="ch.maybites.px1m0d.plug.drawing.effects.icons.IconBasic">
    				<color red="0" green="255" blue="255" alpha="255" />
    				<label>QuickTeacherOne</label>
    				<labelPipe0>Ch00-CC00</labelPipe0>
    				<labelPipe1>Ch00-CC01</labelPipe1>
    				<labelPipe2>Ch00-CC02</labelPipe2>
    				<labelPipe3>Ch00-CC03</labelPipe3>
    				<labelPipe4>Ch00-CC04</labelPipe4>
    				<labelPipe5>Ch00-CC05</labelPipe5>
    				<labelPipe6>Ch00-CC06</labelPipe6>
    				<labelPipe7>Ch00-CC07</labelPipe7>
    				<labelPipe8>Ch00-CC08</labelPipe8>
    			</icon>
    		</display>
			<jobs>
				<job>
					<message trigger="LocalPlugJustCreated">
						<osc ipAddress="world">
							<addressPattern>'/plug/name'</addressPattern>
							<addOscString>''+LocalPlugName</addOscString>
						</osc>
					</message>
				</job>
				<job>
					<message trigger="LocalPlugGotLinked">
						<osc ipAddress="world">
							<addressPattern>'/plug/linkname'</addressPattern>
							<addOscString>''+LinkPlugName</addOscString>
						</osc>
					</message>
				</job>
				<job>
					<message trigger="LocalPipeValue00HasChanged and LocalSwitchIsOn">
						<midi>
							<status type="ControlChange" channel="0" />
							<data>0</data>
							<data>LocalPipeValue00 / 2</data>
						</midi>
					</message>
				</job>
				<job>
					<message trigger="LocalPipeValue01HasChanged and LocalSwitchIsOn">
						<midi>
							<status type="ControlChange" channel="0" />
							<data>1</data>
							<data>LocalPipeValue01 / 2</data>
						</midi>
					</message>
				</job>
				<job>
					<message trigger="LocalPipeValue02HasChanged and LocalSwitchIsOn">
						<midi>
							<status type="ControlChange" channel="0" />
							<data>2</data>
							<data>LocalPipeValue02 / 2</data>
						</midi>
					</message>
				</job>
				<job>
					<message trigger="LocalPipeValue03HasChanged and LocalSwitchIsOn">
						<midi>
							<status type="ControlChange" channel="0" />
							<data>3</data>
							<data>LocalPipeValue03 / 2</data>
						</midi>
					</message>
				</job>
				<job>
					<message trigger="LocalPipeValue04HasChanged and LocalSwitchIsOn">
						<midi>
							<status type="ControlChange" channel="0" />
							<data>4</data>
							<data>LocalPipeValue04 / 2</data>
						</midi>
					</message>
				</job>
				<job>
					<message trigger="LocalPipeValue05HasChanged and LocalSwitchIsOn">
						<midi>
							<status type="ControlChange" channel="0" />
							<data>5</data>
							<data>LocalPipeValue05 / 2</data>
						</midi>
					</message>
				</job>
				<job>
					<message trigger="LocalPipeValue06HasChanged and LocalSwitchIsOn">
						<midi>
							<status type="ControlChange" channel="0" />
							<data>6</data>
							<data>LocalPipeValue06 / 2</data>
						</midi>
					</message>
				</job>
				<job>
					<message trigger="LocalPipeValue07HasChanged and LocalSwitchIsOn">
						<midi>
							<status type="ControlChange" channel="0" />
							<data>7</data>
							<data>LocalPipeValue07 / 2</data>
						</midi>
					</message>
				</job>
				<job>
					<message trigger="LocalPipeValue08HasChanged and LocalSwitchIsOn">
						<midi>
							<status type="ControlChange" channel="0" />
							<data>8</data>
							<data>LocalPipeValue08 / 2</data>
						</midi>
					</message>
				</job>
			</jobs>
		</parameter>
    </plug>
 </plugTree>
